### ISSUE TITLE
[Bug] Icon disappears after update to 6.5.3

### ISSUE THREAD

**Issue by GrayedFox** [getinsomnia/insomnia#1513]
- Insomnia Version: 6.5.3 (installed via aptitude)
- Operating System: Ubuntu 18.04 (LTS)

## Details

Icon disappears (replaced by generic settings icon) after updating to version 6.5.3. To be honest I think I had the aptitude as well as snap package, so I removed both, then reinstalled the snap package only, and the icon is back now.

Got a little suspicious since I noticed in the change log a change to the behaviour of the icon installation (now only done during update). 

Will keep you posted if the next patch/minor version bump removes the icon again!

Best

**Comment by GrayedFox** [comment]
For those landing here from various parts of the interwebs, here's a one line workaround (Ubuntu 18.04 LTS, no guarantees for other *nix flavours):

`sudo apt remove insomnia && sudo snap remove insomnia && sudo snap install insomnia`

[Link for discussion about using sudo for installing snap](https://forum.snapcraft.io/t/run-snap-without-installing-it/1764)

**Comment by josdejong** [comment]
Same here on Linux Mint

**Comment by gschier** [comment]
Hmm, I _did_ change the icon in the last release. Must have goofed something up on Linux. Will take a look!

**Comment by markkrj** [comment]
`~/insomnia $ diff -U0 <(dpkg -c insomnia_6.5.1_amd64.deb | awk '{print$6}') <(dpkg -c insomnia_6.5.3_amd64.deb | awk '{print$6}')`

> --- /dev/fd/63	2019-05-23 11:40:06.474834283 -0300
> +++ /dev/fd/62	2019-05-23 11:40:06.474834283 -0300
> @@ -84,18 +84,3 @@
> -./usr/share/icons/hicolor/128x128/
> -./usr/share/icons/hicolor/128x128/apps/
> -./usr/share/icons/hicolor/128x128/apps/insomnia.png
> -./usr/share/icons/hicolor/48x48/
> -./usr/share/icons/hicolor/48x48/apps/
> -./usr/share/icons/hicolor/48x48/apps/insomnia.png
> -./usr/share/icons/hicolor/32x32/
> -./usr/share/icons/hicolor/32x32/apps/
> -./usr/share/icons/hicolor/32x32/apps/insomnia.png
> -./usr/share/icons/hicolor/256x256/
> -./usr/share/icons/hicolor/256x256/apps/
> -./usr/share/icons/hicolor/256x256/apps/insomnia.png
> -./usr/share/icons/hicolor/512x512/
> -./usr/share/icons/hicolor/512x512/apps/
> -./usr/share/icons/hicolor/512x512/apps/insomnia.png
> -./usr/share/icons/hicolor/16x16/
> -./usr/share/icons/hicolor/16x16/apps/
> -./usr/share/icons/hicolor/16x16/apps/insomnia.png
> +./usr/share/icons/hicolor/0x0/
> +./usr/share/icons/hicolor/0x0/apps/
> +./usr/share/icons/hicolor/0x0/apps/insomnia.png

**Comment by gschier** [comment]
@markkrj can you please explain your comment?

**Comment by markkrj** [comment]
It diffs the 6.5.1 and 6.5.3 packages... 6.5.3 misses all the icons from 6.5.1 and adds hicolor/0x0/... I extracted the icons from 6.5.1 to fix the issue for me temporarily.

**Comment by andreldm** [comment]
I couldn't find anything in the freedesktop specs or gtk implementation telling anything against icons in `hicolor/0x0`, but it seems to be not supported. Check out this icon tester:
https://gist.github.com/andreldm/b971fa0d671a90ae133650f85ce2836a

`gtk_icon_theme_lookup_icon` can't find insomnia's icon when it's on `hicolor/0x0`.

Now run:
```
sudo convert /usr/share/icons/hicolor/0x0/apps/insomnia.png -resize 32x32 /usr/share/icons/hicolor/32x32/apps/insomnia.png
sudo touch /usr/share/icons/hicolor
sudo gtk-update-icon-cache -f /usr/share/icons/hicolor
```
Now the icon tester is able to find the icon as expected.

**Comment by GrayedFox** [comment]
Can confirm that latest update fixes this issue (updating Insomnia this time did not remove Linux icon) @gschier just FYI :+1: thanks!

**Comment by josdejong** [comment]
FIxed indeed, though for some reason the linux ppa (https://support.insomnia.rest/article/23-installation#ubuntu) doesn't have the latest 6.5.4 on my machine. Can be an issue on my side. Manually downloading and installing the .deb file worked.

**Comment by Alcsaw** [comment]
Is this issue is back on 7.0.1?

Icon has disappeared here on Kubuntu 19.04, after upgrading Insomnia and rebooting...

**Comment by josdejong** [comment]
I have the same, icon is gone after installing `7.0.1` on Linux Mint.

**Comment by algomax** [comment]
Yep, the same old issue again with 7.0.1 on Ubuntu 18.04.

**Comment by Alcsaw** [comment]
Is this issue is back on 7.0.1?

Icon has disappeared here on Kubuntu 19.04, after upgrading Insomnia and rebooting...

**Comment by GekovIN** [comment]
Same on ubuntu 16.04

**Comment by TheRealGaspar** [comment]
Here we go again, same. 
Arch 5.3.6-arch1-1-ARCH
Cinnamon 4.2.4

**Comment by mengyaoss77** [comment]
same  on 7.0.2

**Comment by masonlong** [comment]
same on 7.0.3

**Comment by domhnallw** [comment]
Yep, back in 7.0.2/7.0.3. Fixed it by re-creating the icon at all the relevant sizes using the approach by @andreldm and normal service is now resumed.

**Comment by ajyotirmay** [comment]
I guess this issue needs to be re-opened

**Comment by GekovIN** [comment]
> I guess this issue needs to be re-opened

Already re-opened  https://github.com/getinsomnia/insomnia/issues/1717

**Comment by elucidsoft** [comment]
Does it on Windows as well
