### ISSUE TITLE
Insomnia Designer is always reset Environments to default

### ISSUE THREAD

**Issue by kissferenc** [getinsomnia/insomnia#2228]
**Describe the bug**
I am using openapi 3.0.3.
When I clicking on Debug the "OpenApi env" is always created and auto selected. The Base Environment is loosing every custom variable.

**To Reproduce**
1. Create a new Blank document.
2. Edit the document with content:
```
openapi: "3.0.0"
info:
  title: API commands 
  description: This is the API documentation.
  version: 1.0.0
  
paths:
  /login:
    post:

```  
3. Click on the Debug button.
(OpenApi env is automatically created and selected)
4. Copy "OpenApi env" data and Create a new Sub Environment with these data.
5. Delete "OpenApi env".
6. Add a new key/value to Base Environment.
7. Select the new Sub Environment.t
8. Go back to Design.
9. Go again to Debug.

Then the "OpenApi env" is created and selected again, the new key/value variable is missing from Base Environment.

**Expected behavior**
Do not autocreate "OpenApi env" and save the state of Base Environment.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Installation Method: downloaded dmg from website
 - App Version: 2020.2.0

**Comment by kirinnee** [comment]
Issue replicated: 

- OS: Windows 10 Build 2004
- Install Method: MSI
- App Version: 2020.2.0 (5/30/2020)

**Comment by freakinhippie** [comment]
I've encountered this issue as well.

```
OS: Ubuntu 18.04 LTS

Version 2020.3.3
Shell 3.1.13
Node 10.2.0
V8 6.6.346.32
Architecture x64
```

**Comment by kaluznyo** [comment]
Any news on this ? It's very annoying and make this great product unusable because of reset all var

**Comment by GuillaumeDerivery** [comment]
Issue is still here on 2020.5.2 MacOs.

**Comment by a-tonchev** [comment]
Same here. I fixed it when I changed the object attribute from **openapi: '3.0.0'** to **swagger: '2.0.0'**,  but I don't really use all features of openapi, thatswhy for me is kind a working

**Comment by yuriburk** [comment]
Still happening

**Comment by kaluznyo** [comment]
Still happening on 2021.1.1. But a little different. The env 'ENV' seem to be keep (not switching to OpenAPI env like before) But if I have this URI : base_url /cdeop/_.UnikCdeOp where _.UnikCdeOp is a var from env. All it's okay, i can go to Test, make test, be back, still OK.
But if I go to Design, and return to Debug, when I execute request I got "Failed to render request", and my URI is modified with the name from swagger instead of ._UnikCdeOp

**Comment by develohpanda** [comment]
> when I execute request I got "Failed to render request", and my URI is modified with the name from swagger instead of ._UnikCdeOp

Hi @kaluznyo, would you be able to add a gif of what you are seeing? I don't think I understand the last part of it.

**Comment by a-tonchev** [comment]
> Same here. I fixed it when I changed the object attribute from **openapi: '3.0.0'** to **swagger: '2.0.0'**, but I don't really use all features of openapi, thatswhy for me is kind a working

Well, it don't really work, it stop automatically remove all parameters and changes under "Debug", but when I copy new configuration under "Design" it don't do any update... so we have to choose between **no update** or **override everything on any click**

**Comment by kaluznyo** [comment]
> > when I execute request I got "Failed to render request", and my URI is modified with the name from swagger instead of ._UnikCdeOp
> 
> Hi @kaluznyo, would you be able to add a gif of what you are seeing? I don't think I understand the last part of it.

Before going to Debug : 
![Capture d’écran 2021-03-17 à 15 31 17](https://user-images.githubusercontent.com/372462/111484433-0c57da80-8736-11eb-984a-2a80db4d290e.png)

After trying to 'send'
![Capture d’écran 2021-03-17 à 15 31 49](https://user-images.githubusercontent.com/372462/111484744-50e37600-8736-11eb-82f6-6422a66cd1d0.png)

And then 

![Capture d’écran 2021-03-17 à 15 31 31](https://user-images.githubusercontent.com/372462/111484758-53de6680-8736-11eb-804a-f0bb787a174e.png)

**Comment by kaluznyo** [comment]
Still the same with 2021.2.2

**Comment by kaluznyo** [comment]
Same  with 2021.3

**Comment by wdawson** [comment]
Sorry folks! This was incorrectly tagged as a feature request along with other bugs. I'm going back through and cleaning up, sorry for the inconvenience.

**Comment by wdawson** [comment]
I also just reproduced on 2021.4.0 😞

**Comment by visonforcoding** [comment]
Same with 2021.6.0

**Comment by filfreire** [comment]
Hey folks, I couldn't reproduce this one in our [latest stable release (2022.4.2)](https://github.com/Kong/insomnia/releases/tag/core%402022.4.2), closing this issue for now.

@kissferenc (or anyone else) if you're still able to reproduce this with latest versions, please feel free to re-open this issue.
