### ISSUE TITLE
Beta sync new team members fail with "Failed to decrypt data"

### ISSUE THREAD

**Issue by wsrast** [getinsomnia/insomnia#2319]
**Describe the bug**
New team member joining beta sync gets "Failed to decrypt data", and cannot see shared workspaces shared through the new sync service.

**To Reproduce**
1. Add a new team member to the beta sync
2. New user will see a beta shared workspace
3. Sync will initialize
4. All attempts to pull snapshots will fail with "Failed to decrypt data"

If you export your shared workspace as v4 JSON, then have the team member import it, they can see that workspace, but all attempts to pull snapshots fail with the same message.

**Expected behavior**
Sync pull snapshots should work

**Desktop (please complete the following information):**
 - OS: macOS
 - Installation Method: installer
 - App Version 2020.2.2

**Comment by wsrast** [comment]
This continues to be an issue, but I have additional information. The ability to see branches created by others joining the team sync is randomly failing.

Also, I've tried having new team members go through the Insomnia removal process here: https://osxuninstaller.com/uninstall-guides/remove-insomniax-2-1-8/

That does not solve the problem. My guess is that there is something about having preexisting workspaces from the old sync mechanism which is causing the issue. I'm going to try bringing a new team member with no previous data into the team and seeing how this works.

**Comment by apidrop** [comment]
Same problem here. Any update?

**Comment by fremeni** [comment]
Same problem here, any update?

**Comment by develohpanda** [comment]
Hi @wsrast and @fremeni! Especially for team and sync related queries, the best channel is via the support email address - support@insomnia.rest - as it is monitored more closely. Would you mind sending an email through, refer to this GH issue and share any account related information (your email) so that we can have a look at what might be going on? Thank you!

**Comment by 4n70w4** [comment]
The same issue! Failed to decrypt data on pull remote workflow from paid account.
![image](https://user-images.githubusercontent.com/38257723/95253105-97978080-0826-11eb-9d77-7d169b184f84.png)

**Comment by develohpanda** [comment]
@4n70w4 as per the previous comment, please send through your account related information to support@insomnia.rest and we can investigate what is going on.

**Comment by DMarby** [comment]
This issue should have been resolved now on the API end, if you experience this issue in the future, please send an email to support@insomnia.rest.

**Comment by 4n70w4** [comment]
@DMarby problem don't solved! Why closed?

**Comment by 4n70w4** [comment]
You can see logs of your system. I wan't spent my time for make work instead your team.

You keep logs and monitoring? Otherwise, what do you charge for? For a system without production quality control?

**Comment by nijikokun** [comment]
Hi @4n70w4,

We recently resolved a number of issues surrounding this that requires us to work with the users impacted directly through support to get them to a resolved state, this issue is resolved from the API side but we need to get you to a good state on the client side.

Seeing that you are still encountering this issue, and while we do have server logs and server monitoring, as well as database backups and database failover, due to Insomnia's extreme privacy stance in regards to user data (end-to-end encryption) and anti-collection when it comes to analytics (which we have slowly started to introduce as opt-in) in the Insomnia client we do require the users client logs / console logs to best support you, and as a paying customer we have a dedicated support channel for you to provide these instead of through our public open source repository.

Since you are a paying customer, could you please open a ticket through our support system by emailing us at support@insomnia.rest, so we can best support you as a customer, and to ensure your information regarding your account and data stays private.

Thank you!

**Comment by neohq** [comment]
Windows 10 - Insomnia 2020.5.2 still failing
![Screenshot_2570](https://user-images.githubusercontent.com/10179436/107495511-dce30a80-6b98-11eb-9be6-9a6c7ebe4806.png)

**Comment by DMarby** [comment]
Hi @neohq! Please send an email to support@insomnia.rest and we'll be able to help you further.

**Comment by cookiebinary1** [comment]
Guys, I've got solution...

On the instance **where the workspace is running without issues,** do the following:
1. create a duplicate workspace with a new name (**workspace settings => duplicate**)
2. create local project (**setup sync => create local project)**
3. create snapshot (**master / sync => create snapshot**)
4. enter message, select all objects and "**create and push**" (button)

On other instances **where it does "failed to decrypt data"**,
just pull on workspace with new / duplicate name (**workspace name => remote worspaces => pull <new workspace name>**)

This worked for me on multiple instances (different users) with multiple workspaces.

In my opinion, the problem is when two or more users (instances) initialize the remote workspace with the same name. What seemed logical in the transition to a new way of synchronization, but it is not. It needs to be approached as a git workflow. There is also only one initiator of project (repository), the others only clone/pull (then commits/pulls/merges/pushes).

**Comment by mcaballeropinto** [comment]
We sent 3 emails to support@insomnia.rest about sync issues more than a week ago and we still did not received a single reply. 

@DMarby @nijikokun since sending an email to support is the only reasonable solution proposed, can you guys please reply to ours? Our team is big time blocked because of this issue and we are paying customers. The email address used was from a `blanket.ai` domain.

Thanks.

**Comment by develohpanda** [comment]
Hi @mcaballeropinto, sincere apologies for this, not sure what has happened. I have chased up with the team and will make sure that it gets looked at. Thanks!

**Comment by DMarby** [comment]
Hi @mcaballeropinto,

Apologies for the trouble this has caused, I have ensured that your email has gotten a response now, please let me know if you have not received it.
