### ISSUE TITLE
[BUG] Empty parameters are sent without the equal sign for x-www-form-urlencoded requests

### ISSUE THREAD

**Issue by voidmain** [getinsomnia/insomnia#264]
## Overview
- `Insomnia Version:` _5.0.10_
- `Operating System:`  _MacOS 10.12.5_
- `Summary: ` _Empty parameters are sent without an equal sign for x-www-form-urlencoded requests. The specification allows for empty parameters as long as they have an equals sign after the parameter name_

## How To Reproduce
1. _Install a simple echo server like Node http-echo-server and start it up_
2. _Create new POST request with body type `Form URL Encoded`_
3. _Add parameter named `foo` with no value_
4. _Execute the request and notice that the body output in the echo server is `foo` rather than `foo=`_

**Comment by gschier** [comment]
Thanks for reporting this @voidmain. I just pushed a fix for this on #265.

**Comment by CurtisBelt** [comment]
Hello, I am still experiencing this bug.

Ubuntu 17.04
Insomnia 5.7.12

![image](https://user-images.githubusercontent.com/4251760/29291519-7d2bb272-8109-11e7-9fa0-cccddd17b675.png)

**Comment by gschier** [comment]
Hi @voidmain, thanks for reporting!

This is not quite the same bug you mentioned before since that was the request body and your screenshot is of the query string. Did you mean to be using the Body tab?

Omitting `=` sign in the query string is an implementation choice. It is quite common for HTTP clients/servers to omit the equal sign for empty parameters.

**Comment by gschier** [comment]
That being said, it might be worth adding a checkbox or toggle somewhere to change this behavior

**Comment by CurtisBelt** [comment]
@gschier Oops, it's me who added additional comments, not voidmain. I misunderstood his original bug report.

We're going to update our API to allow no equal sign since that's more common to be accepted, like you pointed out.

You can disregard this! Thank you.

**Comment by gschier** [comment]
Woops, I wasn't paying close enough attention. Glad you got it sorted out @CurtisBelt! 😄

**Comment by gonzalo-calandria** [comment]
Hello! I've the same issue with a GET call. The empty parameters are being sent without the equal sign and the API that I'm working on throws me a 400 error because of this. Do we have any solution for this?

**Comment by erkattak** [comment]
I'm facing the same issue. APIs can treat the parameter as a boolean rather than a string due to the missing `=`. As @gschier said, if this can be an optional toggle (per request, or per parameter like Paw does) that would be fantastic.

**Comment by strzyzewski** [comment]
I'm having the exact same problem: 
The server I'm sending my request to, **doesn't recognize query parameters** when they aren't followed by equal signs.

It would be very cool, if we could toggle this behaviour somewhere in the App's settings.

**Comment by Naist4869** [comment]
ASP.NET does insomnia fails but curl work
