### ISSUE TITLE
Query params imported from URL only show after refresh

### ISSUE THREAD

**Issue by RealSting** [getinsomnia/insomnia#2937]
**Describe the bug**
"Import from URL" for query params does not update the UI

**To Reproduce**
1. paste `http://localhost:4000/path?param=test` in the url
2. go to query tab
3. click "import from url"
4. Note that the tab shows the count of query params (1) but the keyvalue table does not update
5. Activate a different request in the sidebar
6. Go back to the previous request
7. Note the query params show correctly

**Expected behavior**
Should update the key value pair table automatically after import

**Screenshots**
![2020-12-18 13 58 20](https://user-images.githubusercontent.com/4312346/102561285-300c8400-4139-11eb-9721-d163a0c2505d.gif)

**OS**
```
Version: Insomnia Core 2020.5.2
Release date: 10/12/2020
OS: Darwin x64 19.6.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
```

**Comment by develohpanda** [comment]
Hi @buddhabas, could you please provide an example URL that fails for you, or a gif/screenshot of the error you see? I was able to import `https://gist.githubusercontent.com/gschier/4e2278d5a50b4bbf1110755d9b48a9f9/raw/801c05266ae102bcb9288ab92c60f52d45557425/petstore-spec.yaml` into Designer 2020.5.2 on Windows.

**Comment by RealSting** [comment]
Thanks :)
If you try https://gist.githubusercontent.com/gschier/4e2278d5a50b4bbf1110755d9b48a9f9/raw/801c05266ae102bcb9288ab92c60f52d45557425/petstore-spec?test=test1
then you click "Import from URL" on Query TAB nothing happen...

I'm on CORE edition

**Comment by develohpanda** [comment]
> If you try [gist.githubusercontent.com/gschier/4e2278d5a50b4bbf1110755d9b48a9f9/raw/801c05266ae102bcb9288ab92c60f52d45557425/petstore-spec?test=test1](https://gist.githubusercontent.com/gschier/4e2278d5a50b4bbf1110755d9b48a9f9/raw/801c05266ae102bcb9288ab92c60f52d45557425/petstore-spec?test=test1)
> then you click "Import from URL" on Query TAB nothing happen...

Hi @buddhabas, can you please share a gif to show exactly what you are seeing? When I go to this link in the browser I get a 404 error because the file is missing the extension `...petstore-spec.yaml`.

**Comment by ARKEOLOGIST** [comment]
Deployed a fix for this.

**Comment by ARKEOLOGIST** [comment]
My previous PR had an issue. It should be resolved now.

**Comment by ARKEOLOGIST** [comment]
@develohpanda any updates?

**Comment by michaelpeterswa** [comment]
This issue still exists on Mac version **Insomnia 2021.4.0**. Looking for any new news like @ARKEOLOGIST

**Comment by HugoLre** [comment]
Still exists on Mac version **2021.4.1**. Any news?

**Comment by sam97** [comment]
Still exists on Windows 10 on a fresh install. FWIW the collection was imported from Postman.

Another thing is that after step 3, if I try to add a new field without refreshing, the old fields get lost.

**Comment by tadomaitis** [comment]
Still exists also on Linux Manjaro, version 2021.4.1.

**Comment by oltronix** [comment]
Still not working for me as well.

`Version: Insomnia 2021.4.1
Release date: 7/7/2021
OS: Windows_NT x64 10.0.19042
Electron: 9.3.5
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0-DEV OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.41.0`

**Comment by llagerlof** [comment]
I am having exactly the same problem. Fresh install.

```
Version: Insomnia 2021.7.2
Release date: 09/12/2021
OS: Windows_NT x64 6.3.9600 (Windows 8.1)
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0-DEV OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.41.0
```

**Comment by victorngeno-gro** [comment]
This is now resolved it seems. The Import from URL button at the bottom/middle of the Query tab works. 
[Screencast from 07-06-23 07:58:33.webm](https://github.com/Kong/insomnia/assets/98331890/3fc47deb-fb3c-4ffe-9a4d-6cea31a48cfa)
I wish this was automated or a setting added to enable automating.

**Comment by NehaMadnani** [comment]
Any possibility to set import query params from url as a default setting anywhere ?

**Comment by ZxBing0066** [comment]
The issue has been resolved in #8643.

Regarding automatic import of query parameters, we do not plan to implement this in the near future as it conflicts with the current behavior.
