### ISSUE TITLE
GraphQL request are adding field "operationName" which results in a failed call.

### ISSUE THREAD

**Issue by matulkum** [getinsomnia/insomnia#5698]
### Expected Behavior

The query string should not have the field "operationName" added.

Eg. Supplied query string: 
```
{ assetCollection { total } }
```
should results in:
```
{"query":" { \n\t assetCollection { total }\n}"}
```

### Actual Behavior

Insomnia adds the field "operationName" to the query string, which causes the request to fail. 

Eg. Supplied query string: 
```
{ assetCollection { total } }
```
results in:
```
{"query":" { \n\t assetCollection { total }\n}","operationName":"Operations"}
```

### Reproduction Steps

Just create a new GraphQL request. Normally this does not happen. But it some point insomnia will start to add this field. And ones it does it keeps adding it all the time.

I do not see anyway to get it to work again, besides deleting the whole request entry and create it completely from scratch.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2022.7.4

### What operating system are you using?

macOS

### Operating System Version

13.0.1

### Installation method

download

**Comment by scottwilloughby** [comment]
We are seeing this same issue in `2022.7.2`, but not in `2022.7.1`

**Comment by mkartchner994** [comment]
In versions after `2022.7.1`, it looks like what is happening is that when using the structured GraphQL query body type, if it is an anonymous operation definition used like:

```gql
{
  user {
    name
  }
}
```

Insomnia is passing the query with operationName as an empty string like:

```json
{"query":"{\n\tuser {\n\t\tname\n\t}\n}","operationName":""}
```

Whereas in version `2022.7.1` it passes it as null:

```json
{"query":"{\n\tuser {\n\t\tname\n\t}\n}","variables":null,"operationName":null}
```

The [GraphQL spec outlines](https://spec.graphql.org/October2021/#GetOperation()) how GraphQL servers should handle the operationName and specifically calls out the cases as either being **null** or an operation name defined in the document. So for an anonymous operation definition, I think operationName should either not be passed, or specifically set to **null**.

**Comment by filfreire** [comment]
Hi folks, this should be fixed on [latest 2022.7.5](https://github.com/Kong/insomnia/releases/tag/core%402022.7.5)

![image](https://user-images.githubusercontent.com/11976836/213691307-5cf75698-934c-4799-8b2a-adada05dd327.png)

![image](https://user-images.githubusercontent.com/11976836/213691345-007b480c-e938-4cfe-8934-b0d1df2d985a.png)

**Comment by vap78** [comment]
I'm still getting this issue.

Version: Insomnia 2022.7.5
Build date: 19.01.2023 г.
OS: Windows_NT x64 10.0.22621
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

Request in Insomnia:
```
query {
	reservations(
		input: {
			driverId: "bd073db9-1de9-4d1c-896c-2a8400e33525"
		}
	) {
		id
	}
}

```

<img width="748" alt="image" src="https://user-images.githubusercontent.com/11094426/214628480-bfc332ce-feb1-47a5-96b7-1e539b711eb2.png">

Actual request sent:

`{"query":"query {\n\treservations(\n\t\tinput: {\n\t\t\tdriverId: \"dc8ef8b1-5591-43f7-9732-29a03fa45cb6\"\n\t\t}\n\t) {\n\t\tid\n\t}\n}\n","operationName":"Operations"}
`

**Comment by amalricBzh** [comment]
> I'm still getting this issue.
> 
> Version: Insomnia 2022.7.5
> Build date: 19.01.2023 г.
> OS: Windows_NT x64 10.0.22621
> Electron: 22.0.0
> Node: 16.17.1 V8: 10.8.168.20-electron.0
> Architecture: x64

Same here. Please reopen this issue !

**Comment by tfutada** [comment]
Same. It won't work. For some reason, newly created requests are not functioning while existing requests are working properly.

**Comment by SteveyPugs** [comment]
Just started experiencing this issue after and update:

```
Version: Insomnia 2022.7.5
Build date: 1/19/2023
OS: Darwin arm64 22.3.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: arm64
```

Returns on GQL queries are:

```json
{
	"errors": [
		{
			"errorType": "BadRequestException",
			"message": "No operation matches the provided operation name ."
		}
	]
}
```

**Comment by mamuf** [comment]
I can confirm it still happened to me in 2022.7.5. But restarting Insomnia helped eventually...

**Comment by joachimbulow** [comment]
Creating a new request (NOT duplicating a bugged one) and copying the query/mutation seems to be a workaround

**Comment by mhiley** [comment]
> Creating a new request (NOT duplicating a bugged one) and copying the query/mutation seems to be a workaround

+1. Running 2022.7.5, when duplicating a query, I get the extra `"operationName":"Operations"` field in the query being sent to the server, which breaks the server. Creating the query from scratch seems to solve it. Another alternative is to use "Copy to Curl", modify the generated curl output, and then paste it into a terminal.

**Comment by SteveyPugs** [comment]
> > Creating a new request (NOT duplicating a bugged one) and copying the query/mutation seems to be a workaround
> 
> +1. Running 2022.7.5, when duplicating a query, I get the extra `"operationName":"Operations"` field in the query being sent to the server, which breaks the server. Creating the query from scratch seems to solve it. Another alternative is to use "Copy to Curl", modify the generated curl output, and then paste it into a terminal.

I second this. This seems to have fixed it.

**Comment by gkristic-vc** [comment]
I wasted time looking for a problem somewhere else, until I realized that it was Insomnia setting this field to `Operations`.

I can't tell for sure whether this happens only to queries created by duplicating another (although this seems to be the case), but I found a simpler workaround than recreating from scratch or going through curl: Notice the "Operations" label below?

![image](https://user-images.githubusercontent.com/32269846/230073501-1cb77500-b170-49e3-a9d6-e8d6a9140c0f.png)

That's the `operationName` you'll get. Just click it and you'll get a dropdown that already includes the correct query name. Select it and you're done. Now the request will pass this validation on the server side.

**Edit:** Your query has to have a name for the name to be pre-populated, like `query whatever { ... }`. If it doesn't, then you'll get an empty list and there's no way to select anything other than "Operations". But Insomnia seems to omit `operationName` when you have an anonymous query anyway, so it's not a problem.

**Comment by washanhanzi** [comment]
> I wasted time looking for a problem somewhere else, until I realized that it was Insomnia setting this field to `Operations`.
> 
> I can't tell for sure whether this happens only to queries created by duplicating another (although this seems to be the case), but I found a simpler workaround than recreating from scratch or going through curl: Notice the "Operations" label below?
> 
> ![image](https://user-images.githubusercontent.com/32269846/230073501-1cb77500-b170-49e3-a9d6-e8d6a9140c0f.png)
> 
> That's the `operationName` you'll get. Just click it and you'll get a dropdown that already includes the correct query name. Select it and you're done. Now the request will pass this validation on the server side.
> 
> **Edit:** Your query has to have a name for the name to be pre-populated, like `query whatever { ... }`. If it doesn't, then you'll get an empty list and there's no way to select anything other than "Operations". But Insomnia seems to omit `operationName` when you have an anonymous query anyway, so it's not a problem.

Version `2023.1.0`, the `Operations` list is empty, but I just clicked it, and it works. Thank you.

**Comment by arsonx** [comment]
> Version `2023.1.0`, the `Operations` list is empty, but I just clicked it, and it works. Thank you.

It also worked for me. Thanks! 

Would like to summarise.. One need to select a blank field from empty dropdown. If not `"operationName":"Operations"` is still being sent. I would still consider this as a bug.

**Comment by Sceat** [comment]
It also prevent the schema from being fetched as the introspection query contains `Operations`

**Comment by xarses** [comment]
Also seeing this in `2023.4.0`. After reading this, it appears to be that it only occurs when duplicating a query, but not always. Duplicating the source again has a chance of succeeding.

@filfreire Can we re-open this or would you like a new issue?

**Comment by filfreire** [comment]
@xarses if possible please create a new issue. If you have any screenshots or recordings of this issue happening that would be helpful. Thank you in advance!

**Comment by kunwardeep** [comment]
I was able to fix this by picking a name from the dropdown next to the schema
<img width="673" alt="Screenshot 2023-09-01 at 10 24 16 am" src="https://github.com/Kong/insomnia/assets/13211086/a8014709-7c8b-4497-8a42-7daa96b05551">

**Comment by mattiasflodin** [comment]
Clicking the "Operations" text either does nothing or shows an empty popup window. I don't see any way of changing it.
![image](https://github.com/Kong/insomnia/assets/788233/430f9a28-a8fb-42d9-b782-474776bc9d54)

**Comment by borys-p** [comment]
This is still happening and can be easily reproduced, could be an edge case left over. 

First, send a GraphQL query with an operation name (can be anything), the query will succeed as the `OperationName` in the JSON payload matches what's in the GraphQL query. Now, remove it from the query and try again. Boom, you get a server error, because the app did not remove `OperationName` from the JSON.

I'm testing with the most recent 8.6.0 version.

cc: @filfreire

**Comment by 0xA-10** [comment]
This caused me a lot of trouble. I'm on v8.6.1. bump

edit: Don't quite have the time to look into the bug report here and all the comments, but my experience has been:

1. When sending an unnamed query, `operationName` will default to "Operations" (it shouldn't default to anything)
2. After sending a named query, the UI's operation name display can become out of sync with the actual `operationName` in the payload. When editing the name of the query in the text editor, the UI's syncing is inconsistent.

Apologies if this is considered a separate issue, please consider looking into this. It basically makes GraphQL unusable in Insomnia, which I think should be treating GQL as a first class citizen. In fairness of not opening a new issue, the "Operations" default string is still lingering.

cc @filfreire

**Comment by webkar86** [comment]
Hello everyone 
to solve this problem, just add a name for the query in front of the word ‘query’.

for example 
instead of writing 

`query{
  continents{
    code
    name
  }
}`
you should write 

`query getCountries{
  continents{
    code
    name
  }
}`
