### ISSUE TITLE
Environment Dropdown No Longer Searches when you type

### ISSUE THREAD

**Issue by ScottCarr73** [getinsomnia/insomnia#5851]
### Expected Behavior

When you open the Environment dropdown, and start typing, it should locate the text in the drop down.

### Actual Behavior

When you type, it no longer highlights the text in the drop down.

### Reproduction Steps

With a list of environments:
* start typing the first couple letters of an environment in the list
* notice that the focus no longer moves to the searched item.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

2023.1.0

### What operating system are you using?

Other Linux

### Operating System Version

Manjaro Linux

### Installation method

yay

### Last Known Working Insomnia version

2022.7.5

**Comment by jamietwells** [comment]
Just another user confirming they are also experiencing this bug since a very recent update:

Insomnia Version
2023.1.0

What operating system are you using?
Windows

Operating System Version
Windows 11

Installation method
chocolatey

Last Known Working Insomnia version
Not sure, was working last week

**Comment by emmanueljourdan** [comment]
Same thing on macOS FWIW.

**Comment by tomas-sk** [comment]
Same here. This was an essential feature for me.

Version: Insomnia 2023.2.2
Build date: 17. 5. 2023
OS: Windows_NT x64 10.0.22621
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by goldfish15** [comment]
I just updated and have also lost this feature. 

Version: Insomnia 2023.2.2
Build date: 5/18/2023
OS: Darwin x64 21.6.0
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

**Comment by zzFluke** [comment]
Still an issue with the latest update. Also, Environment Switch shortcut doesn't work  anymore, neither default (⇧ ⌘ E) nor remapped.

Version: Insomnia 2023.4.0
Build date: 7/4/2023
OS: Darwin x64 22.5.0
Electron: 23.3.9
Node: 18.12.1
V8: 11.0.226.20-electron.0
Architecture: x64

**Comment by johnnovak** [comment]
+1 this should be fixed urgently, please.

**Comment by LicketySpliket** [comment]
Encountering this as well!

**Comment by zzFluke** [comment]
I'm sad to report that this is still an issue. Looks like @gatzjames in 2023.5.6 made an attempt to fix a lot of reported issues around sorting/filtering in sidebar #6323, that resulted in quite large UX/UI modifications, but unfortunately that didn't fix this particular issues with environments list (it was listed as out-of-scope). While typeahead filtering still doesn't work, more over, color tagging of the environments apparently broken, so that became even harder to lookup environment in a large lists manually.

In addition I've noticed that all the versions 2022.7.5+ has some changes that causing substantial slowdowns in the sidebar, such as the simplest action - expand/collapse folder on a large collections takes 2-3sec. Even with the latest above-mentioned refactoring, requests filtering works but with huge latency (5-10sec). All that said renders latest insomnia version unusable for me. Meanwhile rolling back to 2022.7.5 fulfills all my use-cases flawlessly, sacrificing some newly added functionality from the latest versions though.

**Comment by jamietwells** [comment]
@pavkout I think your PR here: 

https://github.com/Kong/insomnia/pull/5615

Caused this regression issue - do you know if it can be reverted to the old dropdown?

**Comment by relgames** [comment]
This issue happens in 2013.4.0 as well. Anyone knows the last good version where this issue didn't exist?

**Comment by subnetmarco** [comment]
As discussed in https://github.com/Kong/insomnia/discussions/6815#discussioncomment-7765772 let's see if we can get this fixed in our December release in a couple of weeks.

**Comment by goldfish15** [comment]
I just noticed in 8.5 I can now search again! It doesn't have the search input field like it used to, but it's definitely highlighting the environments that I start typing for.

**Comment by gatzjames** [comment]
Thanks all for the feedback. Closing as searching now highlights the appropriate environment!
