### ISSUE TITLE
Insomnia forgets gRPC method with server reflection on restart

### ISSUE THREAD

**Issue by Tomasito665** [getinsomnia/insomnia#5892]
### Expected Behavior

- The gRPC request "Select Method" dropdown menu remembers its options.
- The gRPC request "Select Method" dropdown menu remembers the selected option.

### Actual Behavior

- The gRPC request "Select Method" dropdown menu is empty.
- The gRPC request "Select Method" dropdown menu has no method selected.

**Gif animation**
![InsomniaForgetsGrpcMethodIssue](https://user-images.githubusercontent.com/12563382/231738313-d4be617a-daed-4dad-b706-149b133ea4bc.gif)

### Reproduction Steps

1. Run `docker pull tkpd/gripmock:v1.11-beta` to pull gRPC mock server docker image.
2. Create a `service.proto` file with the following contents.

```proto
syntax = "proto3";

message FooRequest {
    string foo = 1;
}

message FooResponse {
    string foo = 1;
}

service FooService {
    rpc Foo (FooRequest) returns (FooResponse);
}
```

3. Create a `stub.json` file in the same directory with the following contents.

```json
{
    "service": "FooService",
    "method": "Foo",
    "input": {
        "matches": {
            "foo": "bar"
        }
    },
    "output": {
        "data": {
            "foo": "bar"
        }
    }
}
```

4. Go to the directory where the `service.proto` file is located and run the following command to spin up the gRPC server.

```bash
docker run --rm -p 4770:4770 \
    -v ${PWD}/stub.json:/stub/stub.json \
    -v ${PWD}/service.proto:/proto/service.proto \
    tkpd/gripmock:v1.11-beta --stub=/stub /proto/service.proto
```

5. Open Insomnia and create a new gRPC request with the host set to `localhost:4770`.
6. Click on the refresh button to use server reflection.
7. Click on "Select Method" and select the `/FooService/Foo` method.
8. Fill in the request body with the following content.
```json
{
    "foo": "bar"
}
```
9. Restart Insomnia and open the same request.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Might be related to this other issue: https://github.com/Kong/insomnia/issues/4291.

### Insomnia Version

2023.1.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.2.1

### Installation method

insomnia.rest

**Comment by ravanscafi** [comment]
I can confirm I also have the same issue.

**Comment by rlindsey28** [comment]
Same issue

**Insomnia Version**

9.3.3

**OS Version**

Sonoma 14.6

**Comment by CurryYangxx** [comment]
Fixed in the latest beta version: https://github.com/Kong/insomnia/releases

**Comment by kushadige** [comment]
> Fixed in the latest beta version: https://github.com/Kong/insomnia/releases

Error still persists; I don’t see the commit you mentioned in the versions.
