### ISSUE TITLE
Every key=value entry dialog has hardcoded headers added

### ISSUE THREAD

**Issue by jathek** [getinsomnia/insomnia#7365]
### Expected Behavior

Entry dialogs to be empty unless I add something

### Actual Behavior

Every entry dialog has the Accept and Host headers as items. So far I've noticed this happening to the Parameters entry, the Form entry, and the Url-Encoded entry. I'm pretty sure it's also happening to the Headers entry, because the tab has the number 2 next to it in the below screenshot, so it's only counting the User-Agent and Content-Type headers.

### Reproduction Steps

Try to use any entry dialog for key=value pairs

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Parameters:
![image](https://github.com/Kong/insomnia/assets/692914/3d73f5c7-b73f-4783-86ba-18740c17c79c)
Multipart Form:
![image](https://github.com/Kong/insomnia/assets/692914/f558a4cb-2065-430f-8e9d-d873b506a502)
Form (URL Encoded):
![image](https://github.com/Kong/insomnia/assets/692914/b4d755db-b791-4a8e-83ee-0a3cdaa62ea4)
Headers:
![image](https://github.com/Kong/insomnia/assets/692914/b5aec7b7-0a49-4acc-b8ab-e6db0a4f5461)

### Insomnia Version

9.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise 23H2 22631.3447

### Installation method

`winget install Insomnia.Insomnia -i`

### Last Known Working Insomnia version

My last Insomnia version was from 2023.5

**Comment by JeroenVdb** [comment]
I have the same problem. When I switch to bulk edit Accept and Host parameters are not visible.

![Screenshot 2024-05-07 at 11 16 44](https://github.com/Kong/insomnia/assets/657797/6b3ab637-65eb-4c12-93f2-4c508fd61e2a)
![Screenshot 2024-05-07 at 11 16 57](https://github.com/Kong/insomnia/assets/657797/e6ff34e3-958d-4095-a12a-f59304b67805)

**Comment by jathek** [comment]
seems like https://github.com/Kong/insomnia/commit/5fb3fc685ddd1c74c9568eb6b8e6909f0aa3eeab fixed this in 9.1.1

**Comment by subnetmarco** [comment]
This issue has been fixed in `9.1.1` indeed.

**Comment by DusanLesan** [comment]
@subnetmarco This is not fixed for me. I experience this and another issue.
All my requests have this two locked headers. I thought that existing requests might be bugged out so I have created new to see if it will be the case for them as well. And it is.
Furthermore, all new requests have `User-Agent` header added without my say so.
![image](https://github.com/Kong/insomnia/assets/20520590/3493d588-ec00-487d-a5ae-e8a599de3d9c)
Running version 9.2.0

**Comment by jackkav** [comment]
This component is old and buggy, but we have a rewrite coming soon that should address your issues, and improve accessibility.
> Furthermore, all new requests have User-Agent header added without my say so.
This is by design, you can opt out by disabling on deleting it.
