### ISSUE TITLE
SSE - Header environment variable is not evaluate before request

### ISSUE THREAD

**Issue by fmeriaux** [getinsomnia/insomnia#7709]
### Expected Behavior

When we set an environment variable (e.g api-key) and we use it in header section on a SSE request, the value of variable should be used in the request header.

### Actual Behavior

The header is present but with the `{{ _.variable_name }}` as a value, instead of the real value

### Reproduction Steps

Create an environment variable with some value
Use this variable as header on a SSE request
Send request and check the timeline - the variable value is not evaluated

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.2

### What operating system are you using?

macOS

### Operating System Version

14.5

### Installation method

download from inso

**Comment by gatzjames** [comment]
Thanks for the feedback @fmeriaux. This is now fixed in the latest beta and will be released in the coming patch version!

**Comment by LucaVazz** [comment]
Hey @gatzjames, unfortunately this problem is appearing again :/

![image](https://github.com/user-attachments/assets/c1245e57-01bf-4d50-8594-3e0e8f5f4456)

Version: Insomnia 10.0.0
Build date: 9.9.2024
OS: Windows_NT x64 10.0.19045
Electron: 31.4.0
Node: 20.16.0
Node ABI: 125
V8: 12.6.228.30-electron.0
Architecture: x64

Could you please look into this issue again?

**Comment by Ziao** [comment]
Using 10.3.0 and still getting this. Only option for now is putting sensitive stuff directly into the header fields. Please reopen and re-assert.

**Comment by roger-schaer** [comment]
Still an issue with the latest version of Insomnia (`11.5.0`):
<img width="228" height="63" alt="Image" src="https://github.com/user-attachments/assets/c52f04a5-d7bc-4826-ba73-f5a9b235ebcf" />

Tried to work around this by defining a pre-request script to set the header, but it seems those also aren't executed for SSE requests?

Thanks in advance for your help!

**Comment by lekhnath** [comment]
cannot use variables in SSE request post json body 


Version: Insomnia 12.3.0
Build date: 1/15/2026
OS: Darwin arm64 25.2.0
Electron: 38.4.0
Node: 22.20.0
Node ABI: 139
V8: 14.0.365.10-electron.0
Architecture: arm64
