### ISSUE TITLE
[Help] Uncaught Error: Maximum update depth exceeded

### ISSUE THREAD

**Issue by BakirRabiaSalma** [getinsomnia/insomnia#838]
> 

- Insomnia Version: ___5.14.9
- Operating System: ___ubuntu 16.0.4

i work with the code source of insomia
when i try to test from it   i get this error
 i don't understand  why i get this error and  how to fix it
## Details

`invariant.js?c115:42 Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (invariant.js?c115:42)
    at requestWork (react-dom.development.js?054f:10833)
    at scheduleWorkImpl (react-dom.development.js?054f:10732)
    at scheduleWork (react-dom.development.js?054f:10689)
    at Object.enqueueSetState (react-dom.development.js?054f:6212)
    at ResponseTimer.Component.setState (react.development.js?7641:237)
    at ResponseTimer._handleUpdateElapsedTime (response-timer.js?d292:25)
    at ResponseTimer.componentDidUpdate (response-timer.js?d292:38)
    at commitLifeCycles (react-dom.development.js?054f:8778)
    at commitAllLifeCycles (react-dom.development.js?054f:9946)`

**Comment by BakirRabiaSalma** [comment]
react 16.0.0

**Comment by gschier** [comment]
Do you have code that I can look at? The error message you provided explains the cause pretty well: "This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate". It seems like you're calling setState in the wrong place.

**Comment by BakirRabiaSalma** [comment]
I don't know at any file this error comes from because when i run insomia ,i put a url and when i clic to send i get this error

**Comment by gschier** [comment]
I just upgraded Electron on my local project and now see this error too. Will fix!

**Comment by gschier** [comment]
I'm not sure why it wasn't occurring before...

**Comment by gschier** [comment]
Should work now on the latest version of the `develop` branch.

**Comment by BakirRabiaSalma** [comment]
ok thank you gschier

**Comment by insub** [comment]
This problem still exists. It seems that the fix of gschier has not been merge into the develop branch?
Development environment on windows 7
@gschier

**Comment by dimitropoulos** [comment]
@insub do you have reproduction steps?  Unfortunately the fix by @luizmariz above will not be viable anymore since componentWillReceiveProps has been remove (as of react 17), we'd need to take one of the options outlined https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

pull requests welcome :), reproduction steps even more welcome.

**Comment by insub** [comment]
@dimitropoulos 
 I'm using UNSAFE_componentWillReceiveProps. it seems to be OK. 
But I'm not sure that's the right way to do it.
