### ISSUE TITLE
Issue with Importing Insomnia V5 YAML Export - "No importers found for file" error

### ISSUE THREAD

**Issue by poojithap11** [getinsomnia/insomnia#8504]
### Expected Behavior

When exporting a collection in Insomnia V5 format, the exported file should be successfully imported into another instance of Insomnia 11.0.0 without errors, and the collection, including all folders, should be restored correctly.

### Actual Behavior

When exporting the collection in Insomnia V5 format (YAML), an error "No importers found for file" is shown when attempting to import the file. Additionally, when exporting as HAR format, none of the folders are imported.

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [ ] Local only

### Insomnia Version

11.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS sequoia version 15.3.2

### Installation method

insomnia.rest

**Comment by Amund93** [comment]
Found a ticket with the same issue, and commeted after more testing here: https://github.com/Kong/insomnia/discussions/8484. Maby merge this ticket into 8484?

**Comment by ahlixinjie** [comment]
Same issue. Anybody can recommend other software?

**Comment by jeremyhalin** [comment]
I have the same issue.

Tried exporting and importing Insomnia v5 collection and it doesn't work.

> Version: Insomnia 11.0.0
Build date: 3/18/2025
OS: Darwin arm64 24.3.0
Electron: 33.3.1
Node: 20.18.1
Node ABI: 130
V8: 13.0.245.24-electron.0
Architecture: arm64

![Image](https://github.com/user-attachments/assets/b1631f77-a4be-480d-b1c1-0e53c0c9b8ce)

**Comment by Liiion911** [comment]
Same issue with inso-cli. Error text:
```
Failed to import Insomnia v5 data _ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "collection",
              0,
              "url"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
...

```

**Comment by DanielH1976** [comment]
So you introduce a new V5 format for exports but forgot to update the import?
Do you even have some sort of QA?

**Comment by smiller0924** [comment]
I'm encountering the same issue.  I can import an older backup.  But cannot import the newer V5.

**Comment by igorbenav** [comment]
Same here

**Comment by vovamod** [comment]
Can confirm same thing.

ZodError: type error

I'm having folders and 2 B.E. vars. Can't import but can export

**Comment by markwimpory** [comment]
this seems pretty critical.  do we know when a fix will be released?

**Comment by liupeng826** [comment]
I have same issue

**Comment by tchauvet** [comment]
Same here.

**Comment by sotosoul** [comment]
Same here ☹ 
Any alternative methods to load the data are welcome 😸

**Comment by Amund93** [comment]
@sotosoul If you have access to a installation file of a previous version (f.ex 10.2), you can reinstall Insomnia and the export/import should work

**Comment by axisd** [comment]
Same here
Export scratchpad collection - login - import and see "No importers found for file"

HAR file export/import fine, but not included folders/env/etc, only req

**Comment by sudheesh-sas** [comment]
I am facing the same issue. Any update on when this will be fixed?

**Comment by pinkycollie** [comment]
# Insomnia Export
# =====================
# * App Version: [Insert Version]
# * Export Format: insomnia.v5.yaml
#...
```

**Comment by jeremyhalin** [comment]
Fixed in `v11.0.2-beta.0`

**Comment by HPODEV** [comment]
i have same issue with 11.37.4 version

**Comment by Mansafreo** [comment]
## App version : v11.0.2-beta.0
## Export Format: insomnia.v5.yaml
I still get the same error. I'm using `v11.0.2-beta.0` on Ubuntu for both the system I'm importing to and from

![Image](https://github.com/user-attachments/assets/6607306f-6302-47ea-8a4a-89722a0956fd)

**Comment by wpp-octavian-sulic** [comment]
Exporter is also 11.0.2
![Image](https://github.com/user-attachments/assets/a54d08b6-1356-41ad-864d-3e9928927c6c)

**Comment by danielbonilha** [comment]
Any fixes? I just exported all my insomnia collections and formatted my HD. 

Yes, now I am blocked on my work because I cant import the files back (11.0.2), and there is no other way to export them on previous version since the HD is all gone.

Sit and cry? Or maybe I can find any volunteer to manually insert back more than 200 endpoints?

**Comment by jjangsky** [comment]
I'm also using Insomnia version 11.0.2, and I'm experiencing the same issue as the others.
When I try to import the exported YAML file, an error occurs.

Do you know when this might be fixed?

**Comment by Mansafreo** [comment]
> I'm also using Insomnia version 11.0.2, and I'm experiencing the same issue as the others. When I try to import the exported YAML file, an error occurs.
> 
> Do you know when this might be fixed?

I just recently updated to 11.1.0 Beta and the imports are now working

Perhaps try out that version

**Comment by lightapps-smart-blocks** [comment]
> > I'm also using Insomnia version 11.0.2, and I'm experiencing the same issue as the others. When I try to import the exported YAML file, an error occurs.
> > Do you know when this might be fixed?
> 
> I just recently updated to 11.1.0 Beta and the imports are now working
> 
> Perhaps try out that version

Installing 11.1.0 Beta worked for me: https://github.com/Kong/insomnia/releases/tag/core%4011.1.0-beta.1
After the imports, I installed the newest version and all set.

**Comment by wisac** [comment]
Now the 11.1.0 beta stopped working as well

**Comment by edniltonjr** [comment]
here the same way, using the beta version

**Comment by mohamed12375** [comment]
Same Issue here, hope they fix it soon

**Comment by miclemabasie** [comment]
I also observed the same issue today

![Image](https://github.com/user-attachments/assets/c4560302-d73a-4c87-ace0-3260ef323d36)

**Comment by miclemabasie** [comment]
For the time being can someone please explain to me how to transfer work from my scratch pad to an online workspace?

**Comment by febryardiansyah** [comment]
facing the same issue here, any update?

**Comment by easkarov** [comment]
Got into the same trouble, any updates?

**Comment by easkarov** [comment]
It looks like devs have forgotten `insomnia-5.ts` among other importers https://github.com/Kong/insomnia/blob/7b5cddb520cb1c77e4442cf52e62d1dc2365790c/packages/insomnia/src/utils/importers/importers/insomnia-4.ts

As we can see that there is [iteration](https://github.com/Kong/insomnia/blob/7b5cddb520cb1c77e4442cf52e62d1dc2365790c/packages/insomnia/src/utils/importers/convert.ts#L24) over them, and [below](https://github.com/Kong/insomnia/blob/7b5cddb520cb1c77e4442cf52e62d1dc2365790c/packages/insomnia/src/utils/importers/convert.ts#L40) there is the error thrown with our lovely exception message

**Comment by filiphanek** [comment]
I just tested Insomnia.Core-11.1.0-beta.1.exe, and the issue is still there. It´s a real pain without functional import. Is there any estimation when the issue will be solved, please?

**Comment by easkarov** [comment]
> I just tested Insomnia.Core-11.1.0-beta.1.exe, and the issue is still there. It´s a real pain without functional import. Is there any estimation when the issue will be solved, please?

You can contribute to solving this problem. I've provided the rough source of the issue above

**Comment by filiphanek** [comment]
I would be happy to do so, but I am not a developer. I am from the product team.  But thanks for pinpointing the reason. I hope someone skilled will be able to fix it. I went back to version 11.0.0 right now.

**Comment by gatzjames** [comment]
Thanks for the feedback. We are fixing this issue on the upcoming v11.1.0

The issue seems to be related with the multiline property in a request body if it is set as multipart/form-data.
As a workaround for now I would suggest:
- Make a copy of your exported file and edit it.
- Find the request that has a `mimeType: multipart/form-data`
- Change the properties that have `multiline: true` to `multiline: "true"`

```yaml
...
    body:
      mimeType: multipart/form-data
      params:
        - name: test
          value: |-
            {
            	"a": 1
            }
          disabled: false
          multiline: "true"
          id: ...
          type: text
...
```

**Comment by easkarov** [comment]
> * Change the properties that have `multiline: true` to `multiline: "true"`

I don't have any `multiline` key, but faced the same issue

**Comment by filiphanek** [comment]
I have it same, no multiline key. But I was able to compare 2 almost identical files with .yaml format, one works in the current Insomnia and one does not. I think I created the working one while switching between 11.0.0 and 11.0.2. I cannot share them as they are large and contain sensitive data. But only difference I found there via Meld tool in non functional file is parameter     ` maxAge`, this one does not exist in the working version at all.

part of file
```
    - key: language
      value: en
      maxAge: 31536000
      domain: xxxxxxxxxxxxxxxx
      path: /
      secure: true
      extensions:
        - SameSite=None
      hostOnly: true
```

sorry, if it is wrong clue, but I do not see anything more there

**Comment by gatzjames** [comment]
Thanks for trying this out and for the info @filiphanek and @easkarov

I will update you as soon as we investigate this in more detail soon

**Comment by gatzjames** [comment]
It seems that `maxAge` on cookies is not creating any issues...
@filiphanek, @easkarov could you share the output of the console (on the app menu View > Toggle DevTools) when importing the failing file with me [similar to this](https://github.com/Kong/insomnia/issues/8504#issuecomment-2747552260)? It doesn't display any data but shows what went wrong with the schema and can help us identify the issue.

**Comment by filiphanek** [comment]
`C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.0.2\resources\app.asar\node_modules\electron-log\src\transports\console.js:93 12:47:40.481 › Failed to import Insomnia v5 data ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "collection",
              2,
              "reflectionApi"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              2,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "collection",
              2,
              "method"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              2,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              2,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_union",
            "unionErrors": [
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "object",
                    "received": "undefined",
                    "path": [
                      "collection",
                      2,
                      "children",
                      12,
                      "reflectionApi"
                    ],
                    "message": "Required"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      2,
                      "children",
                      12,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "string",
                    "received": "undefined",
                    "path": [
                      "collection",
                      2,
                      "children",
                      12,
                      "body",
                      "params",
                      1,
                      "value"
                    ],
                    "message": "Required"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      2,
                      "children",
                      12,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      2,
                      "children",
                      12,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      2,
                      "children",
                      12,
                      "url"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              "collection",
              2,
              "children",
              12
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "collection",
      2
    ],
    "message": "Invalid input"
  },
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "collection",
              4,
              "reflectionApi"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              4,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "collection",
              4,
              "method"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              4,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              4,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_union",
            "unionErrors": [
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "object",
                    "received": "undefined",
                    "path": [
                      "collection",
                      4,
                      "children",
                      15,
                      "reflectionApi"
                    ],
                    "message": "Required"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      4,
                      "children",
                      15,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "string",
                    "received": "undefined",
                    "path": [
                      "collection",
                      4,
                      "children",
                      15,
                      "body",
                      "params",
                      1,
                      "value"
                    ],
                    "message": "Required"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      4,
                      "children",
                      15,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      4,
                      "children",
                      15,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      4,
                      "children",
                      15,
                      "url"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              "collection",
              4,
              "children",
              15
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "collection",
      4
    ],
    "message": "Invalid input"
  },
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "collection",
              9,
              "reflectionApi"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              9,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "collection",
              9,
              "method"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              9,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              9,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_union",
            "unionErrors": [
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "object",
                    "received": "undefined",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "reflectionApi"
                    ],
                    "message": "Required"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "string",
                    "received": "undefined",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "body",
                      "params",
                      2,
                      "name"
                    ],
                    "message": "Required"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "string",
                    "received": "undefined",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "body",
                      "params",
                      2,
                      "value"
                    ],
                    "message": "Required"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "url"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              "collection",
              9,
              "children",
              0
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "collection",
      9
    ],
    "message": "Invalid input"
  }
]
    at get error (C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.0.2\resources\app.asar\node_modules\zod\lib\types.js:55:31)
    at ZodDiscriminatedUnion.parse (C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.0.2\resources\app.asar\node_modules\zod\lib\types.js:160:22)
    at importInsomniaV5Data (insomnia-v5.ts:356:37)
    at import.ts:130:31
    at Array.map (<anonymous>)
    at scanResources (import.ts:123:56)
    at Object.U [as scanForResourcesAction] (import.tsx:104:26)
    at async router.js:4214:19
    at async callLoaderOrAction (router.js:4279:16)
    at async Promise.all (index 0)
    at async defaultDataStrategy (router.js:4142:17)
    at async callDataStrategyImpl (router.js:4173:17)
    at async wC (router.js:2797:17)
    at async bC (router.js:2475:25)
n @ helpers.js:90
setTimeout
(anonymous) @ browserapierrors.js:97
consoleLog @ C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.0.2\resources\app.asar\node_modules\electron-log\src\transports\console.js:93
transport @ C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.0.2\resources\app.asar\node_modules\electron-log\src\transports\console.js:46
runTransport @ C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.0.2\resources\app.asar\node_modules\electron-log\src\log.js:44
runTransports @ C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.0.2\resources\app.asar\node_modules\electron-log\src\log.js:27
log @ C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.0.2\resources\app.asar\node_modules\electron-log\src\log.js:21
importInsomniaV5Data @ insomnia-v5.ts:391
(anonymous) @ import.ts:130
scanResources @ import.ts:123
U @ import.tsx:104
await in U
action @ index.tsx:190
await in action
vt @ router.js:4206
(anonymous) @ router.js:4214
ut @ router.js:4225
callLoaderOrAction @ router.js:4279
resolve @ router.js:4160
(anonymous) @ router.js:4142
defaultDataStrategy @ router.js:4142
callDataStrategyImpl @ router.js:4173
wC @ router.js:2797
bC @ router.js:2475
EC @ router.js:2405
(anonymous) @ index.js:1074
(anonymous) @ index.js:1192
onSubmit @ import-modal.tsx:443
Nb$1 @ react-dom.production.min.js:54
Tb$1 @ react-dom.production.min.js:54
Ub$1 @ react-dom.production.min.js:55
nf$1 @ react-dom.production.min.js:105
se @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
Qk @ react-dom.production.min.js:273
Jb$1 @ react-dom.production.min.js:52
hd$1 @ react-dom.production.min.js:109
fd$1 @ react-dom.production.min.js:74
ed$1 @ react-dom.production.min.js:73
n @ helpers.js:90
`

**Comment by gatzjames** [comment]
🙏 Thanks @filiphanek
From the error message it looks like an issue with the body parameter value being empty and insomnia expecting it to have a value.
Can you try the latest beta [11.1.0-beta.1 📦](https://github.com/Kong/insomnia/releases/tag/core%4011.1.0-beta.1) this should be fixed there

**Comment by filiphanek** [comment]
I made fresh installation of Insomnia and still get same error.

![Image](https://github.com/user-attachments/assets/bc1ef518-9a48-483e-b43c-6d50b4fa7c00)

`

C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.1.0-beta1\resources\app.asar\node_modules\electron-log\src\transports\console.js:93 13:38:21.426 › Failed to import Insomnia v5 data ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "collection",
              9,
              "reflectionApi"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              9,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "collection",
              9,
              "method"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              9,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              9,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_union",
            "unionErrors": [
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "object",
                    "received": "undefined",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "reflectionApi"
                    ],
                    "message": "Required"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "string",
                    "received": "undefined",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "body",
                      "params",
                      2,
                      "name"
                    ],
                    "message": "Required"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      9,
                      "children",
                      0,
                      "url"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              "collection",
              9,
              "children",
              0
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "collection",
      9
    ],
    "message": "Invalid input"
  }
]
    at get error (C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.1.0-beta1\resources\app.asar\node_modules\zod\lib\types.js:55:31)
    at ZodDiscriminatedUnion.parse (C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.1.0-beta1\resources\app.asar\node_modules\zod\lib\types.js:160:22)
    at importInsomniaV5Data (insomnia-v5.ts:356:37)
    at import.ts:130:31
    at Array.map (<anonymous>)
    at scanResources (import.ts:123:56)
    at Object.U [as scanForResourcesAction] (import.tsx:104:26)
    at async router.js:4214:19
    at async callLoaderOrAction (router.js:4279:16)
    at async Promise.all (index 0)
    at async defaultDataStrategy (router.js:4142:17)
    at async callDataStrategyImpl (router.js:4173:17)
    at async wC (router.js:2797:17)
    at async bC (router.js:2475:25)
n @ helpers.js:90
setTimeout
(anonymous) @ browserapierrors.js:97
consoleLog @ C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.1.0-beta1\resources\app.asar\node_modules\electron-log\src\transports\console.js:93
transport @ C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.1.0-beta1\resources\app.asar\node_modules\electron-log\src\transports\console.js:46
runTransport @ C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.1.0-beta1\resources\app.asar\node_modules\electron-log\src\log.js:44
runTransports @ C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.1.0-beta1\resources\app.asar\node_modules\electron-log\src\log.js:27
log @ C:\Users\filip.hanek.NETREX\AppData\Local\insomnia\app-11.1.0-beta1\resources\app.asar\node_modules\electron-log\src\log.js:21
importInsomniaV5Data @ insomnia-v5.ts:391
(anonymous) @ import.ts:130
scanResources @ import.ts:123
U @ import.tsx:104
await in U
action @ index.tsx:190
await in action
vt @ router.js:4206
(anonymous) @ router.js:4214
ut @ router.js:4225
callLoaderOrAction @ router.js:4279
resolve @ router.js:4160
(anonymous) @ router.js:4142
defaultDataStrategy @ router.js:4142
callDataStrategyImpl @ router.js:4173
wC @ router.js:2797
bC @ router.js:2475
EC @ router.js:2405
(anonymous) @ index.js:1074
(anonymous) @ index.js:1192
onSubmit @ import-modal.tsx:443
Nb$1 @ react-dom.production.min.js:54
Tb$1 @ react-dom.production.min.js:54
Ub$1 @ react-dom.production.min.js:55
nf$1 @ react-dom.production.min.js:105
se @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
Qk @ react-dom.production.min.js:273
Jb$1 @ react-dom.production.min.js:52
hd$1 @ react-dom.production.min.js:109
fd$1 @ react-dom.production.min.js:74
ed$1 @ react-dom.production.min.js:73
n @ helpers.js:90


`

**Comment by gatzjames** [comment]
@filiphanek thanks for checking this out and for your help!
It looks like the name is also required in this case which is fixed in latest develop but wasn't released in the latest beta.
The new version will be released soon and fix this problem.
Until then what you can do is find the body parameters that do not have a name in your exported file and either add an empty name or remove them if you don't use them:

```yaml
...
    body:
      mimeType: multipart/form-data
      params:
        - name: "" // <- Add an empty string or remove the parameter completely if it's not intended to be used
          id: ...
...
```

**Comment by easkarov** [comment]
@gatzjames 

I have this output 

```json
[
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "collection",
              12,
              "reflectionApi"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "string",
            "path": [
              "collection",
              12,
              "method"
            ],
            "message": "Expected undefined, received string"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "collection",
              12,
              "body",
              "params",
              1,
              "value"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "string",
            "path": [
              "collection",
              12,
              "method"
            ],
            "message": "Expected undefined, received string"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "string",
            "path": [
              "collection",
              12,
              "method"
            ],
            "message": "Expected undefined, received string"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "string",
            "path": [
              "collection",
              12,
              "url"
            ],
            "message": "Expected undefined, received string"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              12,
              "parameters"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "collection",
      12
    ],
    "message": "Invalid input"
  },
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "collection",
              25,
              "reflectionApi"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "string",
            "path": [
              "collection",
              25,
              "method"
            ],
            "message": "Expected undefined, received string"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "collection",
              25,
              "body",
              "params",
              3,
              "value"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "string",
            "path": [
              "collection",
              25,
              "method"
            ],
            "message": "Expected undefined, received string"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "string",
            "path": [
              "collection",
              25,
              "method"
            ],
            "message": "Expected undefined, received string"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "string",
            "path": [
              "collection",
              25,
              "url"
            ],
            "message": "Expected undefined, received string"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "collection",
      25
    ],
    "message": "Invalid input"
  }
]
```

**Comment by gatzjames** [comment]
Today we released [11.1.0-beta.2 📦](https://github.com/Kong/insomnia/releases/tag/core%4011.1.0-beta.2) which should solve this issue please let us know if it works for you.
@filiphanek @easkarov it should fix the issue you are facing based on the output you shared 🙏

**Comment by sghutke-mdsol** [comment]
I'm getting following error:

```
[
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [],
    "message": "Expected object, received string"
  }
]
```

My Insomnia version is 11.1.0-beta.2

![Image](https://github.com/user-attachments/assets/4991806c-e609-413e-a731-33f153b2c70f)

**Comment by matheushdev** [comment]
> Today we released [11.1.0-beta.2 📦](https://github.com/Kong/insomnia/releases/tag/core%4011.1.0-beta.2) which should solve this issue please let us know if it works for you. [@filiphanek](https://github.com/filiphanek) [@easkarov](https://github.com/easkarov) it should fix the issue you are facing based on the output you shared 🙏

Hello, I tested this new version here and it worked perfectly. When do you plan to make it latest?

**Comment by kirly-af** [comment]
I tried installing 11.1.0-beta.3 and it solved the issue for me.

**Comment by seshan-i360** [comment]
Same here.

**Comment by juan-carvajal** [comment]
Experiencing same error in 11.1.0-beta.3

**Comment by juan-carvajal** [comment]
```
ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "collection",
              3,
              "reflectionApi"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              3,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "collection",
              3,
              "method"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              3,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "undefined",
            "received": "array",
            "path": [
              "collection",
              3,
              "children"
            ],
            "message": "Expected undefined, received array"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_union",
            "unionErrors": [
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "object",
                    "received": "undefined",
                    "path": [
                      "collection",
                      3,
                      "children",
                      23,
                      "reflectionApi"
                    ],
                    "message": "Required"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      3,
                      "children",
                      23,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "boolean",
                    "received": "string",
                    "path": [
                      "collection",
                      3,
                      "children",
                      23,
                      "body",
                      "params",
                      9,
                      "multiline"
                    ],
                    "message": "Expected boolean, received string"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      3,
                      "children",
                      23,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  }
                ],
                "name": "ZodError"
              },
              {
                "issues": [
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      3,
                      "children",
                      23,
                      "method"
                    ],
                    "message": "Expected undefined, received string"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "string",
                    "path": [
                      "collection",
                      3,
                      "children",
                      23,
                      "url"
                    ],
                    "message": "Expected undefined, received string"
                  },
                  {
                    "code": "invalid_type",
                    "expected": "undefined",
                    "received": "array",
                    "path": [
                      "collection",
                      3,
                      "children",
                      23,
                      "parameters"
                    ],
                    "message": "Expected undefined, received array"
                  }
                ],
                "name": "ZodError"
              }
            ],
            "path": [
              "collection",
              3,
              "children",
              23
            ],
            "message": "Invalid input"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "collection",
      3
    ],
    "message": "Invalid input"
  }
]
```

![Image](https://github.com/user-attachments/assets/278eb896-a353-4046-9920-738f455ab961)

**Comment by filiphanek** [comment]
Hello, it works fine for me with beta.3. Thx!

**Comment by adikadic** [comment]
When we can expect the fix for this bug to be released?

**Comment by hakanostrom** [comment]
Confirmed working with 11.1.0 (latest as per date). Exported and imported to myself from my Scratch Pad.
BUT there is still issues. Selecting a partial export (only selecting one of my many folders) still seems to generate a semi-full export. Importing it back to my own instance created unexpected (and strange) "WS"-entries (se image below).
Even more strange is that this bug only seems to arise when using "Insomia v5"-format. The format of HAR works in that way byt has other issues; the folder structure gets "flattened". I.E. al the folders and subfolders are removed and the actual reqest ar placed in the root of the target structure.

![Image](https://github.com/user-attachments/assets/511bb6d9-91b3-4aa2-a52e-b54d28fe650e)

**Comment by Cartman34** [comment]
Upgraded to v11.2.0 and It still doesn't work, neither for the partial export, nor for the full export.

**Comment by Geophysuni** [comment]
Ok, so import of files one by one is not working, but i have solved it by setting a workspace directory in settings, where all my yaml files and it worked somehow.

**Comment by sudheesh-sas** [comment]
Is there a fix in the horizon?

**Comment by andus4n** [comment]
hi; i also have this issue on insomnia v11.4.0. please help!

**Comment by darnel** [comment]
I also experienced `No importers found for file` when importing what I just exported. Perhaps my findings could help someone.
Two of my requests have recursed bodies. Try to search your YAML export for `text:\s*\n\s*mimeType:` and fix the object.
E.g.
```
        body:
          mimeType: text/plain
          text:
            mimeType: text/plain
            text: ""
```
to
```
        body:
          mimeType: text/plain
          text: ""
```

See #9053
